version: '3'
services:
  tomcat:
    image: tomcat:8.0.36-jre8
    platform: linux/x86_64
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Djdk.tls.client.protocols=TLSv1.2
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/lib:/usr/local/tomcat/lib
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./tomcat/bin:/usr/local/tomcat/bin
    command: catalina.sh run
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql